import type { RoadmapItem } from "./types";

const item = (
  id: string,
  module: string,
  feature: string,
  priority: RoadmapItem["priority"],
  sprint: string,
  etaStaging: string | null,
  etaProduction: string | null,
  businessStatus: RoadmapItem["businessStatus"],
  devStatus: RoadmapItem["devStatus"],
  deliveryStatus: RoadmapItem["deliveryStatus"],
  remarks = "",
): RoadmapItem => ({
  id,
  module,
  feature,
  priority,
  sprint,
  etaStaging,
  etaProduction,
  businessStatus,
  devStatus,
  deliveryStatus,
  remarks,
  framework: "SAFe",
});

export const SEED_ITEMS: RoadmapItem[] = [
  item("DCAA-001", "Employee Appraisal", "UI Enhancements & BIGs", "High", "Sprint 10", "2026-05-07", null, "Planned", "Done", "Handover (to Client)"),
  item("DCAA-002", "Employee Appraisal", "KPI Calculation", "High", "Sprint 10", "2026-05-07", null, "Gathering Req", "Done", ""),
  item("DCAA-003", "Employee Appraisal", "UAT & Extra Courses", "High", "Sprint 12", "2026-07-20", null, "In Analysis", "Done", ""),
  item("DCAA-004", "Performance", "UAT Enhancements & BUGs", "High", "Sprint 10", "2026-05-07", null, "Planned", "Done", "Handover (to Client)"),
  item("DCAA-005", "Committees", "Committee CR", "High", "Sprint 11", "2026-07-21", null, "Validation", "Done", ""),
  item("DCAA-006", "Projects", "Filter Unification", "Medium", "Sprint 12", "2026-07-30", null, "Planned", "In Progress", ""),
  item("DCAA-007", "Committees", "Filter Unification", "High", "Sprint 12", "2026-07-30", null, "Planned", "In Progress", ""),
  item("DCAA-008", "Performance", "Filter Unification", "Medium", "Sprint 13", null, null, "Planned", "In Progress", ""),
  item("DCAA-009", "Services", "Filter Unification", "High", "Sprint 13", "2026-07-30", null, "Planned", "In Progress", ""),
  item("DCAA-010", "Innovation", "Filter Unification", "Medium", "Sprint 13", null, null, "Planned", "In Progress", ""),
  item("DCAA-011", "BAU", "Filter Unification", "High", "Sprint 13", "2026-07-30", null, "Planned", "In Progress", ""),
  item("DCAA-012", "Audit", "Filter Unification", "Medium", "Sprint 13", null, null, "Planned", "In Progress", ""),
  item("DCAA-013", "Audit", "Data Migration", "High", "Sprint 11", "2026-07-07", "2026-07-07", "Planned", "Done", "Handover (to Client)"),
  item("DCAA-014", "Committees", "Apply Dubai Font in Meeting Minutes", "High", "Sprint 14", null, null, "", "", ""),
  item("DCAA-015", "Committees", "Enhance Agenda Items Structure", "High", "Sprint 14", null, null, "", "", ""),
  item("DCAA-016", "Committees", "Enhance External Attendees (Guests) Entry Form", "High", "Sprint 14", null, null, "", "", ""),
  item("DCAA-017", "Committees", "Display Meeting Information on Tasks and Decisions", "Medium", "Sprint 14", null, null, "", "", ""),
  item("DCAA-018", "Committees", "Add Concerned Person Field to Tasks", "Medium", "Sprint 14", null, null, "", "", ""),
];
